# ported from .github/workflows/ci.yml w/ forgejo changes
name: CI

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    name: "build, lint, test (${{ matrix.toolchain }})"
    runs-on: "rust"
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy
      - run: cargo test --verbose 

  doc:
    name: "doc"
    runs-on: "rust"
    steps:
      - uses: actions/checkout@v5
      - run: cargo doc

  # check code coverage (disabled in forgejo for now)
  # - fails if coverage drops below 95%
  # - generates "tarpaulin-report.zip" artifact
  coverage:
    name: "coverage"
    runs-on: "rust-x86-64"
    container:
      # note: x86-64-only image
      image: "xd009642/tarpaulin:develop-nightly"
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v5
      # fail if code coverage is below 95%
      #
      # run tarpaulin with single thread and include ignored tests.
      # this is to work around issues with threads for
      # tests::action::test_from_env() in `src/bin/bech32.rs`
      - run: |
          cargo +nightly tarpaulin --engine llvm -j1 -i -o html --timeout 120 --fail-under 95
      - uses: actions/upload-artifact@v5
        with:
          name: tarpaulin-report.zip
          path: tarpaulin-report.html
